services:
    nemishkor.wayforpay:
        class: Nemishkor\Wayforpay\Wayforpay
        autowire: true
        autoconfigure: true

    Nemishkor\Wayforpay\Wayforpay: '@nemishkor.wayforpay'

    nemishkor.wayforpay_request_builder:
        class: Nemishkor\Wayforpay\WayforpayRequestBuilder
        autowire: true
        autoconfigure: true
        arguments:
            - '%wayforpay.merchantSecretKey%'

    Nemishkor\Wayforpay\WayforpayRequestBuilder: '@wayforpay_request_builder'
