services:
    nemishkor.wayforpay:
        class: Nemishkor\Wayforpay\Wayforpay
        autowire: true
        autoconfigure: true

    Nemishkor\Wayforpay\Wayforpay: '@nemishkor.wayforpay'

    nemishkor.wayforpay_request_builder:
        class: Nemishkor\Wayforpay\WayforpayRequestBuilder
        autowire: true
        autoconfigure: true
        arguments:
            - '%wayforpay.merchantSecretKey%'

    Nemishkor\Wayforpay\WayforpayRequestBuilder: '@nemishkor.wayforpay_request_builder'

    nemishkor.wayforpay.request_params_factory:
        class: Nemishkor\Wayforpay\RequestParamsFactory
        autowire: true
        autoconfigure: true
        arguments:
            - '%wayforpay.merchantAccount%'
            - '%wayforpay.merchantDomainName%'

    Nemishkor\Wayforpay\RequestParamsFactory: '@nemishkor.wayforpay.request_params_factory'
